export {cargarInicio} from './inicio/inicio.js';
export {cargarReglas} from './reglas/reglas.js';
export {cargarTipo} from './elegirTipo/elegirTipo.js';
export {cargarJuego} from './juego/juego.js';
export {verificarRespuesta} from './juego/verificarRespuesta.js';
export {pintarRespuesta} from './juego/pintarRespuesta.js';
export {cargarModalOpcion} from './modalOpcionUsuario/modalOpcionUsuario.js';
export {cargarModalPerdio} from './modalPerdio/modalPerdio.js';
export {cargarFinalJuego} from './finalJuego/finalJuego.js';